package com.rd.mtr.enums;

/*
 * @author    : irfan
 * @Date      : 22-May-17
 * @version   : ver. 1.0.0
 *
 * ________________________________________________________________________________________________
 *
 *  Developer				Date		     Version		Operation		Description
 * ________________________________________________________________________________________________
 *
 *
 * ________________________________________________________________________________________________
 *
 * @Project   : multi-tenant-rest
 * @Package   : com.rd.mtr.enums
 * @FileName  : ResponseEnum
 *
 * Copyright ©
 * SolutionDots,
 * All rights reserved.
 *
 */

public enum ResponseEnum {

    // Generic Status
    NOT_FOUND("NOT_FOUND"),
    FOUND("FOUND"),
    SUCCESS("SUCCESS"),
    ALREADY_EXIST("ALREADY_EXIST"),

    //Application Status
    APP_STATUS_UP("APP_STS_SUC_01"),
    APP_STATUS_DOWN("APP_STS_ERR_01"),
    //User Status
    USER_LOGGEDIN_FAILED("USR_AUTH_ERR_01"),
    USER_ACCESS_GRANTED("USR_AUTH_SUC_01"),
    USER_NOT_ACTIVE("USR_ERR_01"),
    USER_LOGGEDIN_FETCHED_FAILED("USR_ERR_03"),
    USER_LOGGEDIN_FETCHED_SUCCESS("USR_SUC_03"),
    USER_LOGGED_OUT_FAILED("USR_ERR_02"),
    USER_LOGGED_OUT_SUCCESS("USR_AUTH_SUC_02"),
    USER_UPDATE_PASSWORD_FAILED("USR_ERR_04"),
    USER_UPDATE_PASSWORD_SUCCESS("USR_SUC_05"),
    USER_UPDATE_PASSWORD_NOT_MATCHED("USR_ERR_05"),
    USER_UPDATE_PASSWORD_OLD_WRONG("USR_ERR_06"),
    USER_CREATE_FAILED("USR_ERR_07"),
    USER_CREATE_SUCCESS("USR_SUC_06"),
    USER_UPDATE_FAILED("USR_ERR_08"),
    USER_UPDATE_SUCCESS("USR_SUC_07"),
    USER_ALREADY_EXIST("CUS_ERR_09"),
    USER_ACTIVATED_FAILED("USR_ERR_10"),
    USER_ACTIVATED_SUCCESS("USR_SUC_08"),
    USER_DE_ACTIVATED_FAILED("USR_ERR_11"),
    USER_DE_ACTIVATED_SUCCESS("USR_SUC_09"),
    USER_CREATE_PASSWORD_FAILED("USR_ERR_09"),
    USER_CREATE_PASSWORD_SUCCESS("USR_SUC_08"),
    USER_ALREADY_CREATE_PASSWORD_ERROR("USR_ERR_10"),
    USER_PROFILE_IMG_UPLOAD_FAILED("USR_ERR_12"),
    USER_PROFILE_IMG_UPLOAD_SUCCESS("USR_SUC_10"),

    //Customer Status
    CUSTOMER_ALL_FETCHED_SUCCESS("CUS_SUC_01"),
    CUSTOMER_CREATE_FAILED("CUS_ERR_01"),
    CUSTOMER_CREATE_SUCCESS("CUS_SUC_02"),
    CUSTOMER_UPDATE_FAILED("CUS_ERR_03"),
    CUSTOMER_UPDATE_SUCCESS("CUS_SUC_03"),
    CUSTOMER_DELETE_FAILED("CUS_ERR_04"),
    CUSTOMER_DELETE_SUCCESS("CUS_SUC_04"),
    CUSTOMER_ALREADY_EXIST("CUS_ERR_02"),

    //Customer Status
    EXPENSE_ALL_FETCHED_SUCCESS("EXP_SUC_01"),
    EXPENSE_CREATE_FAILED("EXP_ERR_01"),
    EXPENSE_CREATE_SUCCESS("EXP_SUC_02"),
    EXPENSE_UPDATE_FAILED("EXP_ERR_03"),
    EXPENSE_UPDATE_SUCCESS("EXP_SUC_03"),
    EXPENSE_DELETE_FAILED("EXP_ERR_04"),
    EXPENSE_DELETE_SUCCESS("EXP_SUC_04"),
    EXPENSE_ALREADY_EXIST("EXP_ERR_02"),

    // Locale Status
    LOCALE_COUNTRY_FETCH_SUCCESS("LOC_COUN_SUC_01"),
    LOCALE_COUNTRY_FETCH_FAILED("LOC_COUN_ERR_01"),
    LOCALE_STATE_FETCH_SUCCESS("LOC_STAT_SUC_01"),
    LOCALE_STATE_FETCH_FAILED("LOC_STAT_ERR_01"),
    LOCALE_CITY_FETCH_SUCCESS("LOC_CITY_SUC_01"),
    LOCALE_CITY_FETCH_FAILED("SYS_CITY_ERR_01"),
    LOCALE_TIMEZONE_FETCH_FAILED("LOC_TIMEZONE_ERR_01"),
    LOCALE_TIMEZONE_FETCH_SUCCESS("LOC_TIMEZONE_SUC_01"),
    //Bank Status
    BANK_ALL_FETCHED_SUCCESS("BANK_SUC_01"),
    BANK_CREATE_FAILED("BANK_ERR_01"),
    BANK_CREATE_SUCCESS("BANK_SUC_02"),
    BANK_UPDATE_FAILED("BANK_ERR_03"),
    BANK_UPDATE_SUCCESS("BANK_SUC_03"),
    BANK_DELETE_FAILED("BANK_ERR_04"),
    BANK_DELETE_SUCCESS("BANK_SUC_04"),
    BANK_ALREADY_EXIST("BANK_ERR_02"),
    //Bank Transfer Status
    BANK_TRA_ALL_FETCHED_SUCCESS("BANK_TRA_SUC_01"),
    BANK_TRA_CREATE_FAILED("BANK_TRA_ERR_01"),
    BANK_TRA_CREATE_SUCCESS("BANK_TRA_SUC_02"),
    //Tax Status
    TAX_ALL_FETCHED_SUCCESS("TAX_SUC_01"),
    TAX_CREATE_FAILED("TAX_ERR_01"),
    TAX_CREATE_SUCCESS("TAX_SUC_02"),
    TAX_UPDATE_FAILED("TAX_ERR_03"),
    TAX_UPDATE_SUCCESS("TAX_SUC_03"),
    TAX_DELETE_FAILED("TAX_ERR_04"),
    TAX_DELETE_SUCCESS("TAX_SUC_04"),
    TAX_ALREADY_EXIST("TAX_ERR_02"),
    //Prefix Status
    PRE_ALL_FETCHED_SUCCESS("PRE_SUC_01"),
    PRE_FETCHED_SUCCESS("PRE_SUC_03"),
    PRE_UPDATE_FAILED("PRE_ERR_01"),
    PRE_UPDATE_SUCCESS("PRE_SUC_02"),
    PRE_ALREADY_EXIST("PRE_ERR_02"),
    //Chart of Accounts Status
    ACCOUNTS_ALL_FETCHED_SUCCESS("ACC_SUC_01"),
    ACCOUNTS_FETCHED_TYPE_SUCCESS("ACC_SUC_05"),
    ACCOUNTS_CREATE_FAILED("ACC_ERR_01"),
    ACCOUNTS_CREATE_SUCCESS("ACC_SUC_02"),
    ACCOUNTS_UPDATE_FAILED("ACC_ERR_03"),
    ACCOUNTS_UPDATE_SUCCESS("ACC_SUC_03"),
    ACCOUNTS_DELETE_FAILED("ACC_ERR_04"),
    ACCOUNTS_DELETE_SUCCESS("ACC_SUC_04"),
    ACCOUNTS_ALREADY_EXIST("ACC_ERR_02"),
    OPENING_BALANCES_SAVE_FAILED("OPN_BAL_ERR_01"),
    OPENING_BALANCES_SAVE_SUCCESS("OPN_BAL_SUC_02"),
    OPENING_BALANCES_DURING_FISCAL_YEAR_SAVE_FAILED("OPN_BAL_ERR_02"),
    OPENING_BALANCES_FETCHED_FAILED("OPN_BAL_ERR_03"),
    OPENING_BALANCES_FETCHED_SUCCESS("OPN_BAL_SUC_03"),
    POST_GENERAL_ENTRY_FAILED("PST_ENT_ERR_01"),
    POST_GENERAL_ENTRY_SUCCESS("PST_ENT_SUC_02"),
    JOURNAL_ENTRY_ALL_FETCHED_SUCCESS("JOUR_GEN_SUC_02"),
    JOURNAL_ENTRY_FETCHED_SUCCESS("JOUR_GEN_SUC_03"),
    //Designation Status
    DES_ALL_FETCHED_SUCCESS("DES_SUC_01"),
    DES_ALL_ACTIVE_FETCHED_SUCCESS("DES_SUC_05"),
    DES_CREATE_FAILED("DES_ERR_01"),
    DES_CREATE_SUCCESS("DES_SUC_02"),
    DES_UPDATE_FAILED("DES_ERR_03"),
    DES_UPDATE_SUCCESS("DES_SUC_03"),
    DES_DELETE_FAILED("DES_ERR_04"),
    DES_DELETE_SUCCESS("DES_SUC_04"),
    DES_ALREADY_EXIST("DES_ERR_02"),
    //Department Status
    DEP_ALL_FETCHED_SUCCESS("DEP_SUC_01"),
    DEP_ALL_ACTIVE_FETCHED_SUCCESS("DEP_SUC_05"),
    DEP_CREATE_FAILED("DEP_ERR_01"),
    DEP_CREATE_SUCCESS("DEP_SUC_02"),
    DEP_UPDATE_FAILED("DEP_ERR_03"),
    DEP_UPDATE_SUCCESS("DEP_SUC_03"),
    DEP_DELETE_FAILED("DEP_ERR_04"),
    DEP_DELETE_SUCCESS("DEP_SUC_04"),
    DEP_ALREADY_EXIST("DEP_ERR_02"),
    //Employee Status
    EMP_ALL_FETCHED_SUCCESS("EMP_SUC_01"),
    EMP_FETCHED_SUCCESS("EMP_SUC_06"),
    EMP_CREATE_FAILED("EMP_ERR_01"),
    EMP_CREATE_SUCCESS("EMP_SUC_02"),
    EMP_UPDATE_FAILED("EMP_ERR_03"),
    EMP_UPDATE_SUCCESS("EMP_SUC_03"),
    EMP_DELETE_FAILED("EMP_ERR_04"),
    EMP_DELETE_SUCCESS("EMP_SUC_04"),
    EMP_ALREADY_EXIST("EMP_ERR_02"),
    EMP_ACTIVATED_FAILED("EMP_ERR_05"),
    EMP_ACTIVATED_SUCCESS("EMP_SUC_07"),
    EMP_DE_ACTIVATED_FAILED("EMP_ERR_06"),
    EMP_DE_ACTIVATED_SUCCESS("EMP_SUC_08"),
    //Payroll Status
    PAY_RUN_ALL_FETCHED_SUCCESS("PAY_RUN_SUC_01"),
    PAY_RUN_FETCHED_SUCCESS("PAY_RUN_SUC_06"),
    PAY_RUN_CREATE_FAILED("PAY_RUN_ERR_01"),
    PAY_RUN_CREATE_SUCCESS("PAY_RUN_SUC_02"),
    PAY_RUN_UPDATE_FAILED("PAY_RUN_ERR_03"),
    PAY_RUN_UPDATE_SUCCESS("PAY_RUN_SUC_03"),
    PAY_RUN_DELETE_FAILED("PAY_RUN_ERR_04"),
    PAY_RUN_DELETE_SUCCESS("PAY_RUN_SUC_04"),
    PAY_RUN_ALREADY_EXIST("PAY_RUN_ERR_02"),
    //Vendor Status
    VEN_ALL_FETCHED_SUCCESS("VEN_SUC_01"),
    VEN_FETCHED_SUCCESS("VEN_SUC_04"),
    VEN_CREATE_FAILED("VEN_ERR_01"),
    VEN_CREATE_SUCCESS("VEN_SUC_02"),
    VEN_UPDATE_FAILED("VEN_ERR_03"),
    VEN_UPDATE_SUCCESS("VEN_SUC_03"),
    VEN_DELETE_FAILED("VEN_ERR_04"),
    VEN_DELETE_SUCCESS("VEN_SUC_04"),
    VEN_ALREADY_EXIST("VEN_ERR_02"),
    VEN_ACTIVATED_FAILED("VEN_ERR_05"),
    VEN_ACTIVATED_SUCCESS("VEN_SUC_07"),
    VEN_DE_ACTIVATED_FAILED("VEN_ERR_06"),
    VEN_DE_ACTIVATED_SUCCESS("VEN_SUC_08"),
    // Expenses Status
    EXP_ALL_FETCHED_SUCCESS("EXP_SUC_01"),
    EXP_CREATE_FAILED("EXP_ERR_01"),
    EXP_CREATE_SUCCESS("EXP_SUC_02"),
    EXP_UPDATE_FAILED("EXP_ERR_03"),
    EXP_UPDATE_SUCCESS("EXP_SUC_03"),
    EXP_DELETE_FAILED("EXP_ERR_04"),
    EXP_DELETE_SUCCESS("EXP_SUC_04"),
    EXP_ALREADY_EXIST("EXP_ERR_02"),
    //System Settings Status
    SYS_SET_ALL_FETCHED_SUCCESS("SYS_SET_SUC_01"),
    SYS_SET_UPDATE_FAILED("SYS_SET_ERR_03"),
    SYS_SET_UPDATE_SUCCESS("SYS_SET_SUC_03"),
    //Product And Services Status
    PR_SER_ALL_FETCHED_SUCCESS("PR_SER_SUC_01"),
    PR_SER_FETCHED_SUCCESS("PR_SER_SUC_05"),
    PR_SER_CREATE_FAILED("PR_SER_ERR_01"),
    PR_SER_CREATE_SUCCESS("PR_SER_SUC_02"),
    PR_SER_UPDATE_FAILED("PR_SER_ERR_03"),
    PR_SER_UPDATE_SUCCESS("PR_SER_SUC_03"),
    PR_SER_DELETE_FAILED("PR_SER_ERR_04"),
    PR_SER_DELETE_SUCCESS("PR_SER_SUC_04"),
    PR_SER_ALREADY_EXIST("PR_SER_ERR_02"),
    BUN_ALL_FETCHED_SUCCESS("BUN_SUC_01"),
    BUN_FETCHED_SUCCESS("BUN_SUC_05"),
    BUN_CREATE_FAILED("BUN_ERR_01"),
    BUN_CREATE_SUCCESS("BUN_SUC_02"),
    BUN_UPDATE_FAILED("BUN_ERR_03"),
    BUN_UPDATE_SUCCESS("BUN_SUC_03"),
    BUN_DELETE_FAILED("BUN_ERR_04"),
    BUN_DELETE_SUCCESS("BUN_SUC_04"),
    BUN_ALREADY_EXIST("BUN_ERR_02"),

    PR_SER_IMG_UPLOAD_FAILED("PR_SER_ERR_05"),
    PR_SER_IMG_UPLOAD_SUCCESS("PR_SER_SUC_05"),
    PR_SER_IMG_DELETE_SUCCESS("PR_SER_DEL_ERR_06"),
    PR_SER_IMG_DELETE_FAILED("PR_SER_DEL_SUC_06"),
    BUN_IMG_UPLOAD_FAILED("BUN_ERR_05"),
    BUN_IMG_UPLOAD_SUCCESS("BUN_SUC_05"),
    BUN_IMG_DELETE_FAILED("BUN_ERR_06"),
    BUN_IMG_DELETE_SUCCESS("BUN_SUC_06"),
    //Stock Adjustments Status
    SA_ALL_FETCHED_SUCCESS("SA_SUC_01"),
    SA_FETCHED_SUCCESS("SA_SUC_05"),
    SA_CREATE_FAILED("SA_ERR_01"),
    SA_CREATE_SUCCESS("SA_SUC_02"),
    SA_ALREADY_EXIST("SA_ERR_02"),
    //Product And Services Category Status
    PR_SER_CAT_ALL_FETCHED_SUCCESS("PR_SER_CAT_SUC_01"),
    PR_SER_CAT_CREATE_FAILED("PR_SER_CAT_ERR_01"),
    PR_SER_CAT_CREATE_SUCCESS("PR_SER_CAT_SUC_02"),
    PR_SER_CAT_UPDATE_FAILED("PR_SER_CAT_ERR_03"),
    PR_SER_CAT_UPDATE_SUCCESS("PR_SER_CAT_SUC_03"),
    PR_SER_CAT_DELETE_FAILED("PR_SER_CAT_ERR_04"),
    PR_SER_CAT_DELETE_SUCCESS("PR_SER_CAT_SUC_04"),
    PR_SER_CAT_ALREADY_EXIST("PR_SER_CAT_ERR_02"),

    //Payment Method Status
    PM_ALL_FETCHED_SUCCESS("PM_ALL_FET_SUC_01"),
    PM_CREATE_SUCCESS("PM_CER_SUC_01"),
    PM_CREATE_FAILED("PM_ERR_01"),
    PM_UPDATE_SUCCESS("PM_UPDATE_SUC_03"),
    PM_UPDATE_FAILED("PM_UPDATE_ERR_03"),
    PM_DELETE_SUCCESS("PM_DEL_SUC_04"),
    PM_DELETE_FAILED("PM_DEL_ERR_04"),
    PM_ALREADY_EXIST("PM_EXIST_01"),

    //Payment Terms Status
    PAYMENT_TERM_ALL_FETCHED_SUCCESS("PAYMENT_TERM_ALL_FET_SUC_01"),
    PAYMENT_TERM_CREATE_FAILED("PAYMENT_TERM_CREATE_ERR_01"),
    PAYMENT_TERM_CREATE_SUCCESS("PAYMENT_TERM_CREATE_SUC_02"),
    PAYMENT_TERM_UPDATE_FAILED("PAYMENT_TERM_UPDATE_ERR_03"),
    PAYMENT_TERM_UPDATE_SUCCESS("PAYMENT_TERM_UPDATE_SUC_03"),
    PAYMENT_TERM_DELETE_FAILED("PAYMENT_TERM_DEL_ERR_04"),
    PAYMENT_TERM_DELETE_SUCCESS("PAYMENT_TERM_DEL_SUC_04"),
    PAYMENT_TERM_ALREADY_EXIST("PAYMENT_TERM_EXIST_01"),

    //Vendor Bill Status
    VEN_BILL_ALL_FETCHED_SUCCESS("VEN_BILL_SUC_01"),
    VEN_BILL_FETCHED_SUCCESS("VEN_BILL_SUC_04"),
    VEN_BILL_CREATE_FAILED("VEN_BILL_ERR_01"),
    VEN_BILL_CREATE_SUCCESS("VEN_BILL_SUC_02"),
    VEN_BILL_UPDATE_FAILED("VEN_BILL_ERR_03"),
    VEN_BILL_UPDATE_SUCCESS("VEN_BILL_SUC_03"),
    VEN_BILL_DELETE_FAILED("VEN_BILL_ERR_04"),
    VEN_BILL_DELETE_SUCCESS("VEN_BILL_SUC_04"),
    VEN_BILL_ALREADY_EXIST("VEN_BILL_ERR_02"),
    VEN_BILL_COMPLETED("VEN_BILL_ERR_05"),

    //Vendor Bill Payment Status
    VEN_BILL_PAYMENT_ALL_FETCHED_SUCCESS("VEN_BILL_PAYMENT_SUC_01"),
    VEN_BILL_PAYMENT_FETCHED_SUCCESS("VEN_BILL_PAYMENT_SUC_04"),
    VEN_BILL_PAYMENT_CREATE_FAILED("VEN_BILL_PAYMENT_ERR_01"),
    VEN_BILL_PAYMENT_CREATE_SUCCESS("VEN_BILL_PAYMENT_SUC_02"),

    //Projects Status
    PRO_ALL_FETCHED_SUCCESS("PRO_SUC_01"),
    PRO_ALL_ACTIVE_FETCHED_SUCCESS("PRO_SUC_05"),
    PRO_CREATE_FAILED("PRO_ERR_01"),
    PRO_CREATE_SUCCESS("PRO_SUC_02"),
    PRO_UPDATE_FAILED("PRO_ERR_03"),
    PRO_UPDATE_SUCCESS("PRO_SUC_03"),
    PRO_DELETE_FAILED("PRO_ERR_04"),
    PRO_DELETE_SUCCESS("PRO_SUC_04"),
    PRO_ALREADY_EXIST("PRO_ERR_02"),
    //Shipping Company Status
    SHI_COM_ALL_FETCHED_SUCCESS("SHI_COM_SUC_01"),
    SHI_COM_ALL_ACTIVE_FETCHED_SUCCESS("SHI_COM_SUC_05"),
    SHI_COM_CREATE_FAILED("SHI_COM_ERR_01"),
    SHI_COM_CREATE_SUCCESS("SHI_COM_SUC_02"),
    SHI_COM_UPDATE_FAILED("SHI_COM_ERR_03"),
    SHI_COM_UPDATE_SUCCESS("SHI_COM_SUC_03"),
    SHI_COM_DELETE_FAILED("SHI_COM_ERR_04"),
    SHI_COM_DELETE_SUCCESS("SHI_COM_SUC_04"),
    SHI_COM_ALREADY_EXIST("SHI_COM_ERR_02"),

    //Estimates Status
    EST_ALL_FETCHED_SUCCESS("EST_SUC_01"),
    EST_FETCHED_SUCCESS("EST_SUC_06"),
    EST_CREATE_FAILED("EST_ERR_01"),
    EST_CREATE_SUCCESS("EST_SUC_02"),
    EST_UPDATE_FAILED("EST_ERR_03"),
    EST_UPDATE_SUCCESS("EST_SUC_03"),
    EST_DELETE_FAILED("EST_ERR_04"),
    EST_DELETE_SUCCESS("EST_SUC_04"),
    EST_ALREADY_EXIST("EST_ERR_02"),
    //Credit Note Status
    CR_NT_ALL_FETCHED_SUCCESS("CR_NT_SUC_01"),
    CR_NT_FETCHED_SUCCESS("CR_NT_SUC_06"),
    CR_NT_CREATE_FAILED("CR_NT_ERR_01"),
    CR_NT_CREATE_SUCCESS("CR_NT_SUC_02"),
    CR_NT_ALREADY_EXIST("CR_NT_ERR_02"),
    CR_NT_REFUND_AMOUNT_CALC_SUCCESS("CR_NT_SUC_03"),

    //Invoices Status
    INV_ALL_FETCHED_SUCCESS("INV_SUC_01"),
    INV_FETCHED_SUCCESS("INV_SUC_06"),
    INV_CREATE_FAILED("INV_ERR_01"),
    INV_CREATE_SUCCESS("INV_SUC_02"),
    INV_UPDATE_FAILED("INV_ERR_03"),
    INV_UPDATE_SUCCESS("INV_SUC_03"),
    INV_CANCEL_FAILED("INV_ERR_04"),
    INV_CANCEL_SUCCESS("INV_SUC_04"),
    INV_ALREADY_EXIST("INV_ERR_02"),
    INV_CASH_FLOW_FETCHED_SUCCESS("INV_CSH_FLOW_SUC_01"),

    //Invoice Payment Status
    INVOICE_PAYMENT_ALL_FETCHED_SUCCESS("INVOICE_PAYMENT_SUC_01"),
    INVOICE_PAYMENT_FETCHED_SUCCESS("INVOICE_PAYMENT_SUC_04"),
    INVOICE_PAYMENT_CREATE_FAILED("INVOICE_PAYMENT_ERR_01"),
    INVOICE_PAYMENT_CREATE_SUCCESS("INVOICE_PAYMENT_SUC_02"),
    INVOICE_PAYMENT_CASH_FLOW_FETCHED_SUCCESS("INVOICE_PAYMENT_CSH_FLOW_SUC_01"),

    //Role Status
    ROLE_ALL_FETCHED_SUCCESS("ROLE_SUC_01"),
    ROLE_ALL_ACTIVE_FETCHED_SUCCESS("ROLE_SUC_02"),
    ROLE_FETCHED_SUCCESS("ROLE_SUC_03"),
    ROLE_CREATE_FAILED("ROLE_ERR_01"),
    ROLE_CREATE_SUCCESS("ROLE_SUC_02"),
    ROLE_UPDATE_FAILED("ROLE_ERR_03"),
    ROLE_UPDATE_SUCCESS("ROLE_SUC_03"),
    ROLE_DELETE_FAILED("ROLE_ERR_04"),
    ROLE_DELETE_SUCCESS("ROLE_SUC_04"),

    // System Status
    INSUFFICIENT_PARAMETERS("SYS_ERR_02"),
    EXCEPTION("SYS_ERR_01"),

    //Organization Status
    ORG_FETCHED_SUCCESS("ORG_SUC_01"),
    ORG_CREATE_FAILED("ORG_ERR_01"),
    ORG_CREATE_SUCCESS("ORG_SUC_02"),
    ORG_UPDATE_FAILED("ORG_ERR_03"),
    ORG_UPDATE_SUCCESS("ORG_SUC_03"),

    // Debit Note/ Payment Return Status
    DEBIT_NOTE_ALL_FETCHED_SUCCESS("DEBIT_NOTE_SUC_01"),
    DEBIT_NOTE_FETCHED_SUCCESS("DEBIT_NOTE_SUC_04"),
    DEBIT_NOTE_CREATE_FAILED("DEBIT_NOTE_ERR_01"),
    DEBIT_NOTE_CREATE_SUCCESS("DEBIT_NOTE_SUC_02"),
    DEBIT_NOTE_UPDATE_FAILED("DEBIT_NOTE_ERR_03"),
    DEBIT_NOTE_UPDATE_SUCCESS("DEBIT_NOTE_SUC_03"),
    DEBIT_NOTE_DELETE_FAILED("DEBIT_NOTE_ERR_04"),
    DEBIT_NOTE_DELETE_SUCCESS("DEBIT_NOTE_SUC_04"),
    DEBIT_NOTE_ALREADY_EXIST("DEBIT_NOTE_ERR_02"),
    DEBIT_NOTE_COMPLETED("DEBIT_NOTE_ERR_05"),
    // Email Templates Status
    EMAIL_TEMP_ALL_FETCHED_SUCCESS("EMAIL_TEMP_SUC_01"),
    EMAIL_TEMP_FETCHED_SUCCESS("EMAIL_TEMP_SUC_04"),
    EMAIL_TEMP_UPDATE_FAILED("EMAIL_TEMP_ERR_03"),
    EMAIL_TEMP_UPDATE_SUCCESS("EMAIL_TEMP_SUC_03"),

    //Organization Status
    DASHBOARD_BANK_ACCOUNTS_FETCHED_SUCCESS("DB_BNK_SUC_01"),
    DASHBOARD_EXPENSE_FETCHED_SUCCESS("DB_EXP_SUC_01"),
    DASHBOARD_CASH_FLOW_FETCHED_SUCCESS("DB_CSH_FLOW_SUC_01"),
    DASHBOARD_INVOICE_FETCHED_SUCCESS("DB_INV_SUC_01");

    private String value;

    ResponseEnum(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
